collections:
- name: community.general
- name: ansible.posix
- name: ansible.netcommon

roles:
- name: vim
  src: hferreira23.vim
- name: bash_it
  src: hferreira23.bash_it
- name: shell
  src: hferreira.shell
